exclude = [
    ".git",
    ".ruff_cache",
    ".venv",
    ".vscode",
    ".idea",
]
line-length = 120
indent-width = 4
target-version = "py313"

[lint]
select = ["ALL"]
ignore = ["D", "RET504", "INP001"]

[lint.flake8-quotes]
docstring-quotes = "double"
inline-quotes = "single"

[format]
quote-style = "single"
indent-style = "space"
line-ending = "auto"
